# Generated by Django 4.1.7 on 2023-03-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
